### ISSUE TITLE
Question: how do you pronounce `ghat` correctly?

### ISSUE THREAD

**Issue by lancewillett** [aduth/Ghat#18]
Is it "gee-hat" or "gat"?

CC @alisterscott

**Comment by alisterscott** [comment]
I say 'gat'

![47393846](https://cloud.githubusercontent.com/assets/128826/22487856/d5a0db14-e85a-11e6-9b91-04c5c5d7a7c4.jpeg)

**Comment by aduth** [comment]
gat.

a play on **G**it**H**ub -> ch**AT**
